### ISSUE TITLE
ServiceBroker options

### ISSUE THREAD

**Issue by icebob** [chameleonbr/node-red-contrib-moleculer#1]
Hi,

first of all, good work! Second thing, I don't know Node-Red very well, just testing. But somehow I can't add ServiceBroker options.
I've tried here:
![image](https://user-images.githubusercontent.com/306521/63799472-7a4a7000-c90c-11e9-87a7-b61c6d62e202.png)
But when it starts, no namespace & transporter in moleculer logs:
     
![image](https://user-images.githubusercontent.com/306521/63799546-93ebb780-c90c-11e9-9ee9-de97be792172.png)

Could you show a flow how it works?

_I've updated to 0.0.3_

**Comment by chameleonbr** [comment]
Hi @icebob, the options node only accept JSON with " on property names.

**Comment by chameleonbr** [comment]
Example: 
{
    "transporter": "redis://localhost:6379",
    "logLevel": "info"
}

**Comment by icebob** [comment]
Ohh really, thanks. I didn't see the error icon. Now it's good, but how can I install package because it said, no `nats` package :) 

![image](https://user-images.githubusercontent.com/306521/63800945-83890c00-c90f-11e9-9d73-2065929c3f23.png)

**Comment by chameleonbr** [comment]
Now you need add transporter module on ~/.node-red folder. Just enter on ~/.node-red and npm install nats or other.

**Comment by icebob** [comment]
Great, works ;)

2 other questions :)

1. How can I use the input values in calling params?
![image](https://user-images.githubusercontent.com/306521/63801550-ddd69c80-c910-11e9-8bea-a20206fae246.png)

2. Why don't see the response in msg?
![image](https://user-images.githubusercontent.com/306521/63801615-0068b580-c911-11e9-8ea7-64c90636a51d.png)

**Comment by chameleonbr** [comment]
Use msg. payload from other node. I will send example, one moment...

**Comment by chameleonbr** [comment]
Import node clicking on top right menu, import and clipboard.
Paste the JSON below.

`[{"id":"86130d4.678e6f","type":"moleculer-request-action","z":"c1e18c68.8a446","broker":"68aef529.83165c","service":"bba75733.f2747","name":"","topic":"add","x":270,"y":240,"wires":[["3f75c224.c43d6e"]]},{"id":"241f577d.9648e8","type":"moleculer-response-action","z":"c1e18c68.8a446","name":"","x":850,"y":240,"wires":[]},{"id":"3f75c224.c43d6e","type":"function","z":"c1e18c68.8a446","name":"","func":"msg.payload = msg.payload.a + msg.payload.b\nreturn msg;","outputs":1,"noerr":0,"x":550,"y":240,"wires":[["241f577d.9648e8"]]},{"id":"9092590b.20314","type":"debug","z":"c1e18c68.8a446","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":830,"y":340,"wires":[]},{"id":"2c99edfb.6108ea","type":"inject","z":"c1e18c68.8a446","name":"","topic":"","payload":"{\"a\":1,\"b\":3}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":260,"y":340,"wires":[["8ef884b.dede078"]]},{"id":"8ef884b.dede078","type":"moleculer-call","z":"c1e18c68.8a446","broker":"68aef529.83165c","name":"","topic":"math.add","options":"{}","x":540,"y":340,"wires":[["9092590b.20314"]]},{"id":"9d823133.492c38","type":"inject","z":"c1e18c68.8a446","name":"Other option","topic":"","payload":"","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":190,"y":400,"wires":[["34ecefc2.a2b82"]]},{"id":"34ecefc2.a2b82","type":"function","z":"c1e18c68.8a446","name":"","func":"\nmsg.payload = {}\nmsg.payload.a = 5;\nmsg.payload.b = 2;\n\n//or\nmsg.payload = {a:5,b:2}\n//on function node json could be without \" duhh \nreturn msg;","outputs":1,"noerr":0,"x":350,"y":400,"wires":[["8ef884b.dede078"]]},{"id":"5ac81efc.2b44a","type":"change","z":"c1e18c68.8a446","name":"","rules":[{"t":"set","p":"payload.a","pt":"msg","to":"10","tot":"num"},{"t":"set","p":"payload.b","pt":"msg","to":"4","tot":"num"}],"action":"","property":"","from":"","to":"","reg":false,"x":380,"y":480,"wires":[["8ef884b.dede078"]]},{"id":"3a9cd0ff.e60d98","type":"inject","z":"c1e18c68.8a446","name":"And other","topic":"","payload":"{}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":180,"y":480,"wires":[["5ac81efc.2b44a"]]},{"id":"68aef529.83165c","type":"moleculer-config","z":"","name":"Nats","options":"{\"transporter\":\"nats://localhost:4222\",\"logLevel\":\"debug\"}"},{"id":"bba75733.f2747","type":"moleculer-service-config","z":"","name":"math","version":"","settings":"{}"}]`

**Comment by chameleonbr** [comment]
If you have problems to paste and import JSON file... 

[flow.txt](https://github.com/chameleonbr/node-red-contrib-moleculer/files/3547835/flow.txt)

**Comment by icebob** [comment]
It seems, the redeploy doesn't stop the previous broker, right?

**Comment by chameleonbr** [comment]
I trying to stop... Maybe I need to insert stop() on other event.

**Comment by chameleonbr** [comment]
NodeRED use payload to transport parameters, the Options on call method, is the call options https://moleculer.services/docs/0.13/actions.html#Call-services

**Comment by icebob** [comment]
Yes, I've figured it now. But in your examples you created the `math.add` action in node-red side?
Because I would like to make a demo which connect to NATS and call the math.add service on a remote node.

**Comment by chameleonbr** [comment]
I 've created math.add on NodeRED, just delete service, and call to a remote node.

**Comment by icebob** [comment]
Ok, now it works. There was an error in random generator Function.
It works for me: 
```js
[
    {
        "id": "3bbdfeae.462e32",
        "type": "tab",
        "label": "Teszt",
        "disabled": false,
        "info": ""
    },
    {
        "id": "5965dcb5.a387c4",
        "type": "moleculer-call",
        "z": "3bbdfeae.462e32",
        "broker": "498d3510.6fb5ec",
        "name": "Math add",
        "topic": "math.add",
        "options": "{}",
        "x": 702,
        "y": 193,
        "wires": [
            [
                "c849088c.2dcbf8"
            ]
        ]
    },
    {
        "id": "658e9c5f.2e85e4",
        "type": "inject",
        "z": "3bbdfeae.462e32",
        "name": "",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 197,
        "y": 193,
        "wires": [
            [
                "7ab3d5bc.d6c26c"
            ]
        ]
    },
    {
        "id": "7ab3d5bc.d6c26c",
        "type": "function",
        "z": "3bbdfeae.462e32",
        "name": "Random number",
        "func": "msg.payload = {\n    a: Math.floor(Math.random() * 100),\n    b: Math.floor(Math.random() * 100)\n};\n\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 457.5,
        "y": 194,
        "wires": [
            [
                "5965dcb5.a387c4"
            ]
        ]
    },
    {
        "id": "c849088c.2dcbf8",
        "type": "debug",
        "z": "3bbdfeae.462e32",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "payload",
        "targetType": "msg",
        "x": 918.5,
        "y": 194,
        "wires": []
    },
    {
        "id": "498d3510.6fb5ec",
        "type": "moleculer-config",
        "z": "",
        "name": "Common",
        "options": "{\"namespace\":\"node-red\",\"transporter\":\"nats://192.168.0.100:4222\"}"
    }
]
```

**Comment by icebob** [comment]
Is it the good way to subscribe a moleculer event?
![image](https://user-images.githubusercontent.com/306521/63804151-cf8b7f00-c916-11e9-865e-dcc74a7757aa.png)
Because it seems it is not registered.

**Comment by chameleonbr** [comment]
Yes, but... I create events on the same service config.

**Comment by icebob** [comment]
Working, awesome! Thanks for you help.

**Comment by chameleonbr** [comment]
It's a initial version, now my focus is on write help and integrate loggers.

**Comment by chameleonbr** [comment]
Hey @icebob, nice work on Moleculer Project, I met him 2 years ago and grew a lot.

**Comment by icebob** [comment]
Thanks! Yes, I'm working on continuously. :)

**Comment by chameleonbr** [comment]
I like NodeRED for your visual part, I thought it would be interesting integrate both.

**Comment by icebob** [comment]
Yes, interesting idea. This is why I've started to try it :)

I've updated to 0.0.4. It seems deploying better, but according to logs, it seems the new broker started before old one stopped:
![image](https://user-images.githubusercontent.com/306521/63805277-60635a00-c919-11e9-8fcf-b288f1bb42fa.png)

**Comment by chameleonbr** [comment]
@icebob, Is there any way to delete a service without stopping the broker? I could try delete service and only stop broker if node is deleted, not restarted.

**Comment by chameleonbr** [comment]
I've added await on stop broker to prevent to start other before stop on version 0.0.5.

**Comment by icebob** [comment]
yes, call the `broker.destroyService`. It needs the service instance but you can get it from name by `broker.getLocalService(name, version)`. [Same code](https://github.com/moleculerjs/moleculer-repl/blob/master/src/commands/destroy.js#L24-L36)

**Comment by chameleonbr** [comment]
You could add it on awesome-moleculer?

**Comment by icebob** [comment]
I've added it! https://github.com/moleculerjs/awesome-moleculer#others
